-- 코드를 입력하세요
SELECT
a.AUTHOR_ID,
a.AUTHOR_NAME,
b.CATEGORY,
sum(b.PRICE * bs.SALES) as TOTAL_SALES
FROM BOOK_SALES bs
left join BOOK b
on bs.BOOK_ID = b.BOOK_ID
left join AUTHOR a
on b.AUTHOR_ID = a.AUTHOR_ID

WHERE bs.SALES_DATE BETWEEN "2022-01-01" AND "2022-01-31"

GROUP BY A.AUTHOR_ID, b.CATEGORY
ORDER BY a.AUTHOR_ID, b.CATEGORY DESC
;