

-- 2022년 3월 오프라인, 온라인 상품 판매 데이터
-- 판매 날짜, 상품ID, 유저ID, 판매량
-- OFFLINE_SALE USER_ID는 NULL표시
-- 판매일 기준 오름차순, 상품ID 오름차순, 유저ID 오름차순
SELECT
DATE_FORMAT(SALES_DATE, "%Y-%m-%d") SALES_DATE,
PRODUCT_ID,
USER_ID,
SALES_AMOUNT
FROM ONLINE_SALE
WHERE SALES_DATE BETWEEN "2022-03-01" AND "2022-03-31"

UNION ALL

SELECT
DATE_FORMAT(SALES_DATE, "%Y-%m-%d") SALES_DATE,
PRODUCT_ID,
NULL USER_ID,
SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SALES_DATE BETWEEN "2022-03-01" AND "2022-03-31"
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID;