-- 코드를 입력하세요
SELECT
    MCDP_CD as "진료과코드",
    COUNT(APNT_NO) as "5월예약건수"
FROM
    APPOINTMENT
WHERE
    -- NVL(APNT_CNCL_YN,'N') = 'N'and 
    APNT_YMD BETWEEN TO_DATE('2022-05-01','YYYY-MM-DD') AND TO_DATE('2022-05-31','YYYY-MM-DD')
GROUP BY MCDP_CD
ORDER BY "5월예약건수","진료과코드"
