-- 코드를 입력하세요
SELECT BOARD_ID,
    WRITER_ID,
    TITLE,
    PRICE,
    CASE WHEN STATUS = 'SALE' THEN '판매중'
        WHEN STATUS = 'RESERVED' THEN '예약중'
        WHEN STATUS = 'DONE' THEN '거래완료'
        ELSE 'error'
    END as STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE between TO_DATE('2022-10-05','YYYY-MM-DD') AND TO_DATE('2022-10-05','YYYY-MM-DD')
ORDER BY BOARD_ID DESC